apiVersion: apps/v1
kind: Deployment
metadata:
  name: betvictor-service-deployment
  namespace: gitlab-runner
spec:
  selector:
    matchLabels:
      app: betvictor-service-pod
  replicas: 2  
  template:
    metadata:
      labels:
        app: betvictor-service-pod
    spec:
      serviceAccountName: betvictor-service-account
      automountServiceAccountToken: false
      containers:
      - name: betvictor-service-pod
        image: betvictor
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /status/live
            port: 32762
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 32762
          initialDelaySeconds: 5
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "300M"
            cpu: "200m"
          requests:
            memory: "200M"
            cpu: "100m"
        ports:
        - containerPort: 32762
          name: port-name

---
apiVersion: v1
kind: Service
metadata:
  name: betvictor-service
  namespace: gitlab-runner
spec:
  type: NodePort
  ports:
  - nodePort: 32762
    port: 32762
    targetPort: 32762
    protocol: TCP
  selector:
    app: betvictor-service-pod

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-cpu
  namespace: gitlab-runner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: betvictor-service-deployment
  minReplicas: 2 
  maxReplicas: 3
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: AverageValue 
        averageValue: 150 
  behavior:
    scaleDown: 
      policies: 
      - type: Pods 
        value: 2 
        periodSeconds: 60 
      - type: Percent
        value: 30 
        periodSeconds: 60
      selectPolicy: Min 
      stabilizationWindowSeconds: 300 
    scaleUp: 
      policies:
      - type: Pods
        value: 3 
        periodSeconds: 70
      - type: Percent
        value: 12 
        periodSeconds: 80
      selectPolicy: Max
      stabilizationWindowSeconds: 0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: gitlab-runner

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-service-configmap-access-role
  namespace: gitlab-runner
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-service-configmap-access-rolebinding
  namespace: gitlab-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-service-configmap-access-role
subjects:
  - kind: ServiceAccount
    name: appp-service-account
    namespace: gitlab-runner
