---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betvictor-service-deployment
  namespace: "betvictor"
spec:
  selector:
    matchLabels:
      app: betvictor-service-pod
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: betvictor-service-pod
    spec:
      serviceAccountName: betvictor-service-account
      automountServiceAccountToken: false
      containers:
      - name: betvictor-service-pod
        image: betvictor
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 1     
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 1     
          periodSeconds: 5
          failureThreshold: 3  
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "300M"
            cpu: "200m"
          requests:
            memory: "200M"
            cpu: "100m"
        ports:
        - containerPort: 80
          name: port-name

---
apiVersion: v1
kind: Service
metadata:
  name: betvictor-service
  namespace: "betvictor"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: betvictor-service-pod

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: betvictor-service-autoscaling
  namespace: "betvictor"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: betvictor-service-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization 
          averageUtilization: 50

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: betvictor-service-account
  namespace: "betvictor"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: betvictor-service-configmap-access-role
  namespace: "betvictor"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: betvictor-service-configmap-access-rolebinding
  namespace: "betvictor"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: betvictor-service-configmap-access-role
subjects:
  - kind: ServiceAccount
    name: betvictor-service-account
    namespace: "betvictor"